### ISSUE TITLE
Menu text diapering when changing colour scheme in customizer 

### ISSUE THREAD

**Issue by JustinDMathew** [lightspeeddevelopment/lsx-theme#28]
I noticed this issue when testing the customizer for the LSX theme. This is on the [lsx-demo site](http://lsx-demo.lsdev.biz)

The issue was found on **LSX version 1.3** while using **Wordpress 4.3.**

When a user selects a colour scheme in the customiser other than the default the menu text either changes or disappears completely. This is noticed partially for the last colour (Orange) in the colour pallet. See attached screenshots. 

**From:**
![lsx1](https://cloud.githubusercontent.com/assets/13352603/9628228/c013f300-5169-11e5-85b5-83ecf0e8d698.PNG)

**To this**
![lsx2](https://cloud.githubusercontent.com/assets/13352603/9628233/c3992982-5169-11e5-9cad-24db19ed3b4c.PNG)

Warwick could you please take the next step on this one by scheduling.

**Comment by krugazul** [comment]
Justin spoke to me privately,  he tested, this is now fixed.
